name: My first demo workflow
on: 
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github'
  pull_request:
    branches: 
      - main 
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  build:
    name: 'Build the code'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Dump github context
      run: |
        echo "${{ toJSON(github) }}"
    - name: Dump env context
      run: |
        echo "${{ toJSON(env) }}"
    - name: Dump matrix context
      run: |
        echo "${{ toJSON(matrix) }}"
    - name: Dump runner context
      run: |
        echo "${{ toJSON(runner) }}"
    - run: |
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
        echo "🎉 The job was triggered by event: ${{ github.event_name }}"
    - uses: action/checkout@latest
    - name: 'List files in directory'
      run: |
        echo "List all files in repo ${{ github.repository }}"
        tree
        
 
    
