name: My first demo workflow
on: 
  push:
    branches: 
      - main
    branches-ignore: 
      - .github
  pull_request:
    branches: 
      - main 
  schedule:
    - cron: '* * *'
    
jobs:
  build:
    name: 'Build the code'
    runs-on: ubuntu-latest
    
    steps:
    - name: Dump runner context
      uses: echo ${{toJSON(runner)}}
    - name: Dump env context
      uses: echo ${{toJSON(env)}}
    - name: Dump matrix context
      uses: echo ${{toJSON(matrix)}}
    - name: Dump github context
      uses: echo ${{toJSON(github)}}
    
